#### Lists

In [1]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [2]:
numbers[0:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
numbers[0:10:1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
numbers[0:10:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
numbers[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
numbers[:10:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
numbers[1:19:2]

[1, 3, 5, 7, 9, 11, 13, 15, 17]

In [8]:
numbers[::2]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
numbers[::-2]

[19, 17, 15, 13, 11, 9, 7, 5, 3, 1]

In [10]:
numbers[10:2:-2]

[10, 8, 6, 4]

In [11]:
len(numbers)

20

#### Common Built-in Functions

In [12]:
max(5, 3, 7, 10)

10

In [13]:
round(10.312, 1)

10.3

In [14]:
sum([1, 2, 4])

7

#### Lists

In [15]:
array = [3, 4, 5, 6]
array

[3, 4, 5, 6]

In [16]:
array * 2

[3, 4, 5, 6, 3, 4, 5, 6]

In [17]:
array + [7]

[3, 4, 5, 6, 7]

In [18]:
['a', 'b', 'c', 3, 4, 5.0]

['a', 'b', 'c', 3, 4, 5.0]

In [19]:
str_array = ['a', 'b', 'c']
str_array

['a', 'b', 'c']

In [20]:
array + str_array

[3, 4, 5, 6, 'a', 'b', 'c']

In [21]:
for num in array:
   print(num, end = ' ')

3 4 5 6 

In [22]:
for num in [10, 20, 30]:
    print(num, end = ' ')

10 20 30 

In [23]:
x = range(10, 20, 2)
for num in x:
    print(num, end = ' ')

10 12 14 16 18 

#### Numpy

In [24]:
import numpy as np

In [25]:
numpy_array = np.array([1, 2, 3, 4])
numpy_array

array([1, 2, 3, 4])

In [26]:
np.asarray(['a', 'b', 'c', 3, 4, 5.0])

array(['a', 'b', 'c', '3', '4', '5.0'], dtype='<U32')

In [27]:
numpy_array + 3

array([4, 5, 6, 7])

In [28]:
np.sum(numpy_array)

10

In [29]:
np.max(numpy_array)

4

In [30]:
np.mean(numpy_array)

2.5

In [31]:
np.pi

3.141592653589793

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a / b

array([0.25, 0.4 , 0.5 ])

In [33]:
str_array = np.array([19, 20, 'a', 'ac', 'ab', 'a9'])
str_array

array(['19', '20', 'a', 'ac', 'ab', 'a9'], dtype='<U11')

In [34]:
np.sort(str_array)

array(['19', '20', 'a', 'a9', 'ab', 'ac'], dtype='<U11')

In [35]:
for item in str_array:
    print(item, end = ' ')

19 20 a ac ab a9 

In [36]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array[numpy_array<5]

array([1, 2, 3, 4])

#### Ranges

In [37]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(2,5)

array([2, 3, 4])

In [39]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [40]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

#### 2D Arrays

In [41]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [42]:
A[1]

[5, 6, 7, 8]

In [43]:
A[1][0]

5

In [44]:
A[1][0::2]

[5, 7]

In [45]:
len(A)

3

In [46]:
len(A[0])

4

In [47]:
[[0]*5]*3

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [48]:
for row in A:
    print(row)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [49]:
for row in A:
    for item in row:
        print(item, end=' ')
    print()

1 2 3 4 
5 6 7 8 
9 10 11 12 


#### 2D Numpy Arrays

In [50]:
B = np.array(A)
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
B.shape

(3, 4)

In [52]:
B.shape[1]

4

In [53]:
B[1]

array([5, 6, 7, 8])

In [54]:
B[1,0]

5

In [55]:
B[1,0::2]

array([5, 7])

In [56]:
B[1:,:-1]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [57]:
C = np.array([1, 2, 3, 4])
C.shape

(4,)

In [58]:
C = np.expand_dims(C, axis=0)
C.shape

(1, 4)

In [59]:
C = np.array([1, 2, 3, 4])
C = np.expand_dims(C, axis=1)
C.shape

(4, 1)

In [60]:
D = np.array([5, 6, 7, 8])
D = np.expand_dims(D, axis=1)
D.shape

(4, 1)

In [61]:
E = np.concatenate((C, D), axis=1)
E.shape

(4, 2)

In [62]:
E

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [63]:
for row in E:
    print(row)

[1 5]
[2 6]
[3 7]
[4 8]


In [64]:
for row in E:
    for item in row:
        print(item, end=' ')
    print()

1 5 
2 6 
3 7 
4 8 
